theme = "nord"

[editor]
line-number = "relative"
true-color = true
mouse = true
auto-format = true
auto-completion = true
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

#[language-server.yaml-language-server.config.yaml]
#format = { enable = true }
#validation = true

#[language-server.yaml-language-server.config.yaml.schemas]
#"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
#"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"
