theme = "nord"

[editor]
line-number = "relative"
true-color = true
mouse = true
auto-format = true
auto-completion = true
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"



[keys.insert]
"A-down" = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "move_line_down",
] # moves the current line down

"A-up" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "move_line_up",
] # moves the current line up
